# Generated by Django 4.2.7 on 2026-01-31 03:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cedula', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Cédula')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='Email')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('password', models.CharField(max_length=128, verbose_name='Contraseña')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('fecha_inicio', models.DateTimeField(verbose_name='Fecha de Inicio')),
                ('ubicacion', models.CharField(max_length=255, verbose_name='Ubicación')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='eventos/', verbose_name='Imagen')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('cobra_comision', models.BooleanField(default=False, verbose_name='Cobra Comisión')),
                ('valor_comision', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor de Comisión')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Lote')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('cantidad_total', models.PositiveIntegerField(verbose_name='Cantidad Total')),
                ('cantidad_vendida', models.PositiveIntegerField(default=0, verbose_name='Cantidad Vendida')),
                ('orden', models.PositiveIntegerField(default=1, verbose_name='Orden')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='core.evento', verbose_name='Evento')),
            ],
            options={
                'verbose_name': 'Lote',
                'verbose_name_plural': 'Lotes',
                'ordering': ['evento', 'orden'],
                'unique_together': {('evento', 'orden')},
            },
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cantidad_entradas', models.PositiveIntegerField(default=1, verbose_name='Cantidad de Entradas')),
                ('monto_subtotal', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Subtotal')),
                ('monto_comision', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Comisión')),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto Total')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('EXPIRADO', 'Expirado')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('mp_preference_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Preference ID (MP)')),
                ('mp_payment_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Payment ID (MP)')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Aprobación')),
                ('fecha_expiracion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Expiración')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes', to='core.cliente', verbose_name='Cliente')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes', to='core.evento', verbose_name='Evento')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes', to='core.lote', verbose_name='Lote')),
            ],
            options={
                'verbose_name': 'Orden',
                'verbose_name_plural': 'Órdenes',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('usada', models.BooleanField(default=False, verbose_name='Usada')),
                ('fecha_uso', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Uso')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entradas', to='core.cliente', verbose_name='Cliente')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entradas', to='core.lote', verbose_name='Lote')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entradas', to='core.orden', verbose_name='Orden')),
                ('usuario_validador', models.ForeignKey(blank=True, help_text='Usuario de staff que validó la entrada', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Validado por')),
            ],
            options={
                'verbose_name': 'Entrada',
                'verbose_name_plural': 'Entradas',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
