# Generated by Django 4.2.7 on 2026-01-31 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='imagen_qr',
            field=models.ImageField(blank=True, null=True, upload_to='qrs/', verbose_name='Imagen QR'),
        ),
    ]
